version: '3'
services:
  web:
    container_name: docker-django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /code
    ports:
      - 8000:8000
    volumes:
      - .:/code #カレントディレクトリを/codeにマウント
    depends_on:
      - db
    networks:
      - my_network

  db:
    container_name: docker-django-db
    image: mysql:8.0.33-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: 'Asia/Tokyo'
    env_file: .env
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
